/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module tan_multiplier_16_sec (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16;

  wire [31:0] Y [0:15];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];

  //Multipliers:

  wire signed [36:0]
    w1,
    w4,
    w3,
    w5,
    w8,
    w7,
    w9,
    w16,
    w15,
    w19,
    w21,
    w32,
    w29,
    w35,
    w40,
    w41,
    w48,
    w51,
    w192,
    w171,
    w336,
    w345,
    w2,
    w12,
    w24,
    w42,
    w64,
    w82,
    w112;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w3 = w4 - w1;
  assign w5 = w1 + w4;
  assign w8 = w1 << 3;
  assign w7 = w8 - w1;
  assign w9 = w1 + w8;
  assign w16 = w1 << 4;
  assign w15 = w16 - w1;
  assign w19 = w3 + w16;
  assign w21 = w5 + w16;
  assign w32 = w1 << 5;
  assign w29 = w32 - w3;
  assign w35 = w3 + w32;
  assign w40 = w5 << 3;
  assign w41 = w1 + w40;
  assign w48 = w3 << 4;
  assign w51 = w3 + w48;
  assign w192 = w3 << 6;
  assign w171 = w192 - w21;
  assign w336 = w21 << 4;
  assign w345 = w9 + w336;
  assign w2 = w1 << 1;
  assign w12 = w3 << 2;
  assign w24 = w3 << 3;
  assign w42 = w21 << 1;
  assign w64 = w1 << 6;
  assign w82 = w41 << 1;
  assign w112 = w7 << 4;

  assign Y[0] = w2[36:5];
  assign Y[1] = w5[36:5];
  assign Y[2] = w9[36:5];
  assign Y[3] = w12[36:5];
  assign Y[4] = w15[36:5];
  assign Y[5] = w19[36:5];
  assign Y[6] = w24[36:5];
  assign Y[7] = w29[36:5];
  assign Y[8] = w35[36:5];
  assign Y[9] = w42[36:5];
  assign Y[10] = w51[36:5];
  assign Y[11] = w64[36:5];
  assign Y[12] = w82[36:5];
  assign Y[13] = w112[36:5];
  assign Y[14] = w171[36:5];
  assign Y[15] = w345[36:5];

endmodule //tan_multiplier_16_sec

