/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module tan_multiplier_32_sec_0 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16;

  wire [31:0] Y [0:15];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];

  //Multipliers:

  wire signed [36:0]
    w1,
    w4,
    w3,
    w5,
    w8,
    w7,
    w9,
    w16,
    w15,
    w11,
    w24,
    w25,
    w32,
    w27,
    w6,
    w12,
    w14,
    w18,
    w20,
    w22,
    w30;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w3 = w4 - w1;
  assign w5 = w1 + w4;
  assign w8 = w1 << 3;
  assign w7 = w8 - w1;
  assign w9 = w1 + w8;
  assign w16 = w1 << 4;
  assign w15 = w16 - w1;
  assign w11 = w3 + w8;
  assign w24 = w3 << 3;
  assign w25 = w1 + w24;
  assign w32 = w1 << 5;
  assign w27 = w32 - w5;
  assign w6 = w3 << 1;
  assign w12 = w3 << 2;
  assign w14 = w7 << 1;
  assign w18 = w9 << 1;
  assign w20 = w5 << 2;
  assign w22 = w11 << 1;
  assign w30 = w15 << 1;

  assign Y[0] = w1[36:5];
  assign Y[1] = w3[36:5];
  assign Y[2] = w4[36:5];
  assign Y[3] = w6[36:5];
  assign Y[4] = w7[36:5];
  assign Y[5] = w9[36:5];
  assign Y[6] = w11[36:5];
  assign Y[7] = w12[36:5];
  assign Y[8] = w14[36:5];
  assign Y[9] = w16[36:5];
  assign Y[10] = w18[36:5];
  assign Y[11] = w20[36:5];
  assign Y[12] = w22[36:5];
  assign Y[13] = w25[36:5];
  assign Y[14] = w27[36:5];
  assign Y[15] = w30[36:5];

endmodule //tan_multiplier_32_sec_0

